name: payment npm publish

on:
  release:
    types: [published]
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/payment

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Changed to v2, as it's the most stable version at my last update.

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Prune and Install Dependencies
        run: |
          pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Compile
        run: pnpm build

      - name: Publish
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
